/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BagRouteImport } from './routes/bag'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WishlistShareRouteImport } from './routes/wishlist.share'
import { Route as OrderConfirmationOrderNumberRouteImport } from './routes/order-confirmation.$orderNumber'
import { Route as DebugAnalyticsRouteImport } from './routes/debug.analytics'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminStorefrontRouteImport } from './routes/admin.storefront'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminIncompleteRouteImport } from './routes/admin.incomplete'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCreateOrderRouteImport } from './routes/admin.create-order'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAbandonedRouteImport } from './routes/admin.abandoned'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistShareRoute = WishlistShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => WishlistRoute,
} as any)
const OrderConfirmationOrderNumberRoute =
  OrderConfirmationOrderNumberRouteImport.update({
    id: '/order-confirmation/$orderNumber',
    path: '/order-confirmation/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebugAnalyticsRoute = DebugAnalyticsRouteImport.update({
  id: '/debug/analytics',
  path: '/debug/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorefrontRoute = AdminStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncompleteRoute = AdminIncompleteRouteImport.update({
  id: '/incomplete',
  path: '/incomplete',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateOrderRoute = AdminCreateOrderRouteImport.update({
  id: '/create-order',
  path: '/create-order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedRoute = AdminAbandonedRouteImport.update({
  id: '/abandoned',
  path: '/abandoned',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/wishlist': typeof WishlistRouteWithChildren
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/create-order': typeof AdminCreateOrderRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/help': typeof AdminHelpRoute
  '/admin/incomplete': typeof AdminIncompleteRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/storefront': typeof AdminStorefrontRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/order-confirmation/$orderNumber': typeof OrderConfirmationOrderNumberRoute
  '/wishlist/share': typeof WishlistShareRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/wishlist': typeof WishlistRouteWithChildren
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/create-order': typeof AdminCreateOrderRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/help': typeof AdminHelpRoute
  '/admin/incomplete': typeof AdminIncompleteRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/storefront': typeof AdminStorefrontRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/order-confirmation/$orderNumber': typeof OrderConfirmationOrderNumberRoute
  '/wishlist/share': typeof WishlistShareRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/wishlist': typeof WishlistRouteWithChildren
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/create-order': typeof AdminCreateOrderRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/help': typeof AdminHelpRoute
  '/admin/incomplete': typeof AdminIncompleteRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/storefront': typeof AdminStorefrontRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/order-confirmation/$orderNumber': typeof OrderConfirmationOrderNumberRoute
  '/wishlist/share': typeof WishlistShareRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bag'
    | '/checkout'
    | '/login'
    | '/wishlist'
    | '/admin/abandoned'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/create-order'
    | '/admin/customers'
    | '/admin/help'
    | '/admin/incomplete'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/storefront'
    | '/admin/support'
    | '/admin/users'
    | '/category/$slug'
    | '/debug/analytics'
    | '/order-confirmation/$orderNumber'
    | '/wishlist/share'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/bag'
    | '/checkout'
    | '/login'
    | '/wishlist'
    | '/admin/abandoned'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/create-order'
    | '/admin/customers'
    | '/admin/help'
    | '/admin/incomplete'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/storefront'
    | '/admin/support'
    | '/admin/users'
    | '/category/$slug'
    | '/debug/analytics'
    | '/order-confirmation/$orderNumber'
    | '/wishlist/share'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bag'
    | '/checkout'
    | '/login'
    | '/wishlist'
    | '/admin/abandoned'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/create-order'
    | '/admin/customers'
    | '/admin/help'
    | '/admin/incomplete'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/storefront'
    | '/admin/support'
    | '/admin/users'
    | '/category/$slug'
    | '/debug/analytics'
    | '/order-confirmation/$orderNumber'
    | '/wishlist/share'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BagRoute: typeof BagRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  WishlistRoute: typeof WishlistRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  DebugAnalyticsRoute: typeof DebugAnalyticsRoute
  OrderConfirmationOrderNumberRoute: typeof OrderConfirmationOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/share': {
      id: '/wishlist/share'
      path: '/share'
      fullPath: '/wishlist/share'
      preLoaderRoute: typeof WishlistShareRouteImport
      parentRoute: typeof WishlistRoute
    }
    '/order-confirmation/$orderNumber': {
      id: '/order-confirmation/$orderNumber'
      path: '/order-confirmation/$orderNumber'
      fullPath: '/order-confirmation/$orderNumber'
      preLoaderRoute: typeof OrderConfirmationOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/analytics': {
      id: '/debug/analytics'
      path: '/debug/analytics'
      fullPath: '/debug/analytics'
      preLoaderRoute: typeof DebugAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storefront': {
      id: '/admin/storefront'
      path: '/storefront'
      fullPath: '/admin/storefront'
      preLoaderRoute: typeof AdminStorefrontRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incomplete': {
      id: '/admin/incomplete'
      path: '/incomplete'
      fullPath: '/admin/incomplete'
      preLoaderRoute: typeof AdminIncompleteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create-order': {
      id: '/admin/create-order'
      path: '/create-order'
      fullPath: '/admin/create-order'
      preLoaderRoute: typeof AdminCreateOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned': {
      id: '/admin/abandoned'
      path: '/abandoned'
      fullPath: '/admin/abandoned'
      preLoaderRoute: typeof AdminAbandonedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAbandonedRoute: typeof AdminAbandonedRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCreateOrderRoute: typeof AdminCreateOrderRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminHelpRoute: typeof AdminHelpRoute
  AdminIncompleteRoute: typeof AdminIncompleteRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminStorefrontRoute: typeof AdminStorefrontRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonedRoute: AdminAbandonedRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCreateOrderRoute: AdminCreateOrderRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminHelpRoute: AdminHelpRoute,
  AdminIncompleteRoute: AdminIncompleteRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminStorefrontRoute: AdminStorefrontRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WishlistRouteChildren {
  WishlistShareRoute: typeof WishlistShareRoute
}

const WishlistRouteChildren: WishlistRouteChildren = {
  WishlistShareRoute: WishlistShareRoute,
}

const WishlistRouteWithChildren = WishlistRoute._addFileChildren(
  WishlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BagRoute: BagRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  WishlistRoute: WishlistRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  DebugAnalyticsRoute: DebugAnalyticsRoute,
  OrderConfirmationOrderNumberRoute: OrderConfirmationOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
